<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Mountain Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0.2" os="" host="DESKTOP-MCR2EQO"><DocLocation><![CDATA[D:\!UFT Scripts\Scripts\Forms\Forms_006]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[Forms_006]]></DName>
<Res><![CDATA[Res4]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:16]]></Time>
<TimeTick>1610472676</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Run "chrome.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "chrome.exe",1]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:16]]></Time>
<TimeTick>1610472676</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="10" status="Passed" >
<Disp><![CDATA[Run "chrome.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="4" nRep="9" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[RecallMax™ Login]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:17]]></Time>
<TimeTick>1610472677</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[RecallMax™ Login.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:17]]></Time>
<TimeTick>1610472677</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="13" >
<Disp><![CDATA[RecallMax™ Login.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[RecallMax™ Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:17]]></Time>
<TimeTick>1610472677</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[username.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["51771admin"]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:17]]></Time>
<TimeTick>1610472677</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="17" >
<Disp><![CDATA[username.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Welcome2"]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:17]]></Time>
<TimeTick>1610472677</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="20" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:17]]></Time>
<TimeTick>1610472677</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="23" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="16" >
<Disp><![CDATA[RecallMax™ Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="12" >
<Disp><![CDATA[RecallMax™ Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Dashboard]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:19]]></Time>
<TimeTick>1610472679</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Key Indicators]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:19]]></Time>
<TimeTick>1610472679</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Logout.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["visible", True, True, 3000]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:19]]></Time>
<TimeTick>1610472679</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="28" >
<Disp><![CDATA[Logout.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Message Settings.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:19]]></Time>
<TimeTick>1610472679</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="31" Source="Action1" SourceLine="31" >
<Disp><![CDATA[Message Settings.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="27" >
<Disp><![CDATA[Key Indicators]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="26" >
<Disp><![CDATA[Dashboard]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Patient Form]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:20]]></Time>
<TimeTick>1610472680</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Patient Message Settings]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:20]]></Time>
<TimeTick>1610472680</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Patient Message Settings.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["visible", True, True, 3000]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:20]]></Time>
<TimeTick>1610472680</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="36" Source="Action1" SourceLine="32" >
<Disp><![CDATA[Patient Message Settings.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Patient Message Settings]]></Obj>
<Details plainTxt="False" ><![CDATA[WebElement]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:20]]></Time>
<TimeTick>1610472680</TimeTick>
<HtmlStep rID="T20">
<HTML><![CDATA[<html>
<head>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8"/>
<base href=""/>
<link rel="stylesheet" href="Results.css"/>
</head>
<body bgcolor="#ffffff" leftmargin="20" marginwidth="20" topmargin="10" marginheight="10" vlink="#9966cc">
<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr><td height="1" class="bg_midblue"></td></tr>
	<tr><td height="30"><span class="hl1"> Standard Checkpoint "Patient Message Settings": </span><span class="PassedHigh">Passed</span></td></tr>
	<tr><td height="2" class="bg_darkblue"></td></tr>
	<tr><td height="10"></td></tr>
	<tr><td><span class="text"><b>Date and Time:</b> 1/12/2021 - 10:31:20</span></td></tr>
		
	<tr><td height="15"></td></tr>
</table>
<!--Until here code from report media-->
<table border="0" cellpadding="0" cellspacing="0" width="100%" id=TABLE2><tr height="1"><td height="1" class="bg_gray_ccc"></td></tr><tr><td height="5"></td></tr></table><table>
	<tr><td height="30"><span class="hl2"> Details</span></td></tr><tr><td height="5"></td></tr>
</table>
<table border="0" cellpadding="3" cellspacing="1" width="100%" bgcolor="#666699">
	<tr>
		<td bgcolor="white">
		<table border="0" cellpadding="3" cellspacing="0" width="100%">
<tr><td  class="hl3">Patient Message Settings Results&nbsp;</td></tr>
<tr><th colspan=2 height=1 class="bg_darkblue"></th></tr>
<TR>
				<td height=1 class="tablehl">Property Name&nbsp;&nbsp;</td>
				<td height=1 class="tablehl">Property Value&nbsp;&nbsp;</td>
</TR>
			<TR><th colspan=2 height=1 class="bg_gray_eee"></th></TR><tr><th colspan=2 height=1 class="bg_darkblue"></th></tr>
<TR>
				<TD class="Text" Title="">innertext&nbsp;</TD>
				<TD class="Text" Title="">Patient Message Settings &nbsp;</TD>
</TR>
			<TR><th colspan=2 height=1 class="bg_gray_eee"></th></TR>
		</table>
		</td>
	</tr>
</table>
</body></html>]]></HTML>
<TimeTick>1610472680</TimeTick>
<NodeArgs eType="Verification" icon="10" nRep="39" status="Passed" Source="Action1" SourceLine="33" >
<Disp><![CDATA[Checkpoint "Patient Message Settings"]]></Disp>
</NodeArgs>
</HtmlStep>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ virtualWaitingRoom ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:21]]></Time>
<TimeTick>1610472681</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="42" Source="Action1" SourceLine="40" >
<Disp><![CDATA[[ virtualWaitingRoom ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ newPatientEmail ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:21]]></Time>
<TimeTick>1610472681</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="44" Source="Action1" SourceLine="40" >
<Disp><![CDATA[[ newPatientEmail ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[ newPatientSms ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:21]]></Time>
<TimeTick>1610472681</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="46" Source="Action1" SourceLine="40" >
<Disp><![CDATA[[ newPatientSms ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[[ todaysPatientEmail ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:21]]></Time>
<TimeTick>1610472681</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="48" Source="Action1" SourceLine="40" >
<Disp><![CDATA[[ todaysPatientEmail ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ todaysPatientSms ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:21]]></Time>
<TimeTick>1610472681</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="50" Source="Action1" SourceLine="40" >
<Disp><![CDATA[[ todaysPatientSms ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[[ reminderEmail ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:21]]></Time>
<TimeTick>1610472681</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="52" Source="Action1" SourceLine="40" >
<Disp><![CDATA[[ reminderEmail ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ reminderSms ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:21]]></Time>
<TimeTick>1610472681</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="54" Source="Action1" SourceLine="40" >
<Disp><![CDATA[[ reminderSms ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ oneWeekEmail ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:21]]></Time>
<TimeTick>1610472681</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="56" Source="Action1" SourceLine="40" >
<Disp><![CDATA[[ oneWeekEmail ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[[ oneWeekSms ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:21]]></Time>
<TimeTick>1610472681</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="58" Source="Action1" SourceLine="40" >
<Disp><![CDATA[[ oneWeekSms ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[[ twoWeekEmail ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:21]]></Time>
<TimeTick>1610472681</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="60" Source="Action1" SourceLine="40" >
<Disp><![CDATA[[ twoWeekEmail ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[[ twoWeekSms ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:21]]></Time>
<TimeTick>1610472681</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="62" Source="Action1" SourceLine="40" >
<Disp><![CDATA[[ twoWeekSms ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ dueEmail ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:21]]></Time>
<TimeTick>1610472681</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="64" Source="Action1" SourceLine="40" >
<Disp><![CDATA[[ dueEmail ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[[ dueSms ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:21]]></Time>
<TimeTick>1610472681</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="66" Source="Action1" SourceLine="40" >
<Disp><![CDATA[[ dueSms ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[[ lateEmail ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:21]]></Time>
<TimeTick>1610472681</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="68" Source="Action1" SourceLine="40" >
<Disp><![CDATA[[ lateEmail ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[[ lateSms ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:21]]></Time>
<TimeTick>1610472681</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="70" Source="Action1" SourceLine="40" >
<Disp><![CDATA[[ lateSms ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[[ overdueEmail ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:22]]></Time>
<TimeTick>1610472682</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="72" Source="Action1" SourceLine="40" >
<Disp><![CDATA[[ overdueEmail ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[[ overdueSms ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:22]]></Time>
<TimeTick>1610472682</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="74" Source="Action1" SourceLine="40" >
<Disp><![CDATA[[ overdueSms ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[[ pastDueEmail ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:22]]></Time>
<TimeTick>1610472682</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="76" Source="Action1" SourceLine="40" >
<Disp><![CDATA[[ pastDueEmail ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[[ pastDueSms ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:22]]></Time>
<TimeTick>1610472682</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="78" Source="Action1" SourceLine="40" >
<Disp><![CDATA[[ pastDueSms ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[[ reactivateEmail ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:22]]></Time>
<TimeTick>1610472682</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="80" Source="Action1" SourceLine="40" >
<Disp><![CDATA[[ reactivateEmail ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[[ reactivateSms ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[1/12/2021 - 10:31:22]]></Time>
<TimeTick>1610472682</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="82" Source="Action1" SourceLine="40" >
<Disp><![CDATA[[ reactivateSms ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[1/12/2021 - 10:34:40]]></Time>
<TimeTick>1610472880</TimeTick>
<NodeArgs eType="General" icon="12" nRep="83" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="38" status="Passed" Source="Action1" SourceLine="33" >
<Disp><![CDATA[Patient Message Settings]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="35" status="Passed" Source="Action1" SourceLine="32" >
<Disp><![CDATA[Patient Message Settings]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="34" status="Passed" Source="Action1" SourceLine="32" >
<Disp><![CDATA[Patient Form]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="1/12/2021 - 10:31:16" eTime="1/12/2021 - 10:34:40" passed="2" failed="0" warnings="0" ></Summary>

<ActionMaintenanceSummary Action="Action1" Objects="0" Updated="0" Added="0" LinesTotal="0" LinesUpdated="0">
</ActionMaintenanceSummary><NodeArgs eType="StartAction" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="1/12/2021 - 10:31:14" eTime="1/12/2021 - 10:34:40" passed="2" failed="0" warnings="0" stopped="True" ></Summary>

<TestMaintenanceSummary ObjectsAdded="0" ObjectsUpdated="0" StepsUpdated="0" StepsComments="0">
</TestMaintenanceSummary><NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test Forms_006 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>